apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-workshop-service1
  labels:
    app: k8s-workshop-service1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-workshop-service1
  template:
    metadata:
      labels:
        app: k8s-workshop-service1
    spec:
      containers:
      - name: k8s-workshop-service1
        image: blabs-k8s-workshop-service1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 5000
        #   initialDelaySeconds: 2
        #   periodSeconds: 10

