#---------------service1---------------
apiVersion: v1
kind: Service
metadata:
  name: k8s-workshop-load-service1
  labels:
    app: k8s-workshop-service1
spec:
  type: LoadBalancer
  selector:
    app: k8s-workshop-service1
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000
---
#---------------service2---------------
apiVersion: v1
kind: Service
metadata:
  name: k8s-workshop-load-service2
  labels:
    app: k8s-workshop-service2
spec:
  type: LoadBalancer
  selector:
    app: k8s-workshop-service2
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000

