#---------------service1---------------
apiVersion: v1
kind: Service
metadata:
  name: k8s-workshop-node-service1
  labels:
    app: k8s-workshop-service1
spec:
  type: NodePort
  selector:
    app: k8s-workshop-service1
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30100
---
#---------------service2---------------
apiVersion: v1
kind: Service
metadata:
  name: k8s-workshop-node-service2
  labels:
    app: k8s-workshop-service2
spec:
  type: NodePort
  selector:
    app: k8s-workshop-service2
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30100
