# -----------service1----------------
apiVersion: v1
kind: Service
metadata:
  name: k8s-workshop-clusterip-service1
spec:
  type: ClusterIP
  selector:
    app: k8s-workshop-service1
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000

---
#---------------service2---------------
apiVersion: v1
kind: Service
metadata:
  name: k8s-workshop-clusterip-service2
spec:
  type: ClusterIP
  selector:
    app: k8s-workshop-service2
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
